# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/cypher
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

resilience4j.circuitbreaker.instances:
sefaz:
failure-rate-threshold: 50
wait-duration-in-open-state= 30s
sliding-window-size= 10